name: flutter_public_repository
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  get_it: ^7.2.0
  collection: ^1.17.0
  freezed_annotation: ^2.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  package_info_plus: ^3.0.3
  network_info_plus: ^3.0.2
  device_info_plus: ^8.1.0
  go_router: ^6.0.7
  pretty_dio_logger: ^1.3.1
  sqlite3_flutter_libs: 0.5.5
  path_provider: 2.0.9
  path: ^1.8.2
  freezed: ^2.3.2
  drift: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.7.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  injectable_generator: ^2.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/environment/
